### ISSUE TITLE
Not loading required modules

### ISSUE THREAD

**Issue by DudeLooksLikeASupportTech** [cisagov/Sparrow#10]
# 🐛 Bug Report

Running the script out of C:\Scripts on a Windows 2012 R2 server.  We have a local AD domain sync'd with AzureAD, and I'm logged into local server with a Domain Admin account.  Get the error below for the CloudConnect, AzureAD, and MSOnline modules...

Import-Module : The specified module 'CloudConnect' was not loaded because no valid module file was found in any
module directory.
At C:\scripts\Sparrow.ps1:13 char:13
+             Import-Module -Name $ReqModule
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (CloudConnect:String) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand

Output of $env:PSModulePath is shown below...
PS C:\scripts> $env:PSModulePath
C:\Users\netfrank.KISH\Documents\WindowsPowerShell\Modules;C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules\;C:\Program Files\Microsoft Azure AD Sync\Bin\;C:\Program Files\Microsoft Azure AD Connect Health Sync Agent\PowerShell\

**Comment by plaintextcity** [comment]
I had this problem as well, because I had one of the modules installed but an older version.  Updating them in reverse order as below allowed me to get through the module check (if you try to update CloudConnect first, it tries to update MSOnline but not with -allowclobber so it fails).

```
install-module -name MSOnline -force -allowclobber
install-module -name AzureAD -force -allowclobber
install-module -name cloudconnect -force -allowclobber
```

**Comment by DudeLooksLikeASupportTech** [comment]
Here's the results of trying to to use the install-module command...

PS C:\scripts> install-module -name MSOnline -force -allowclobber
install-module : The term 'install-module' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
At line:1 char:1
+ install-module -name MSOnline -force -allowclobber
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (install-module:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by NoMoreFood** [comment]
@DudeLooksLikeASupportTech What version of PowerShell are you running?  $PSVersionTable

**Comment by Qualley-MN** [comment]
I had to set TLS 1.2 - https://devblogs.microsoft.com/powershell/powershell-gallery-tls-support/

[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

**Comment by DudeLooksLikeASupportTech** [comment]
PS C:\scripts> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      4.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   6.3.9600.19170
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}
PSRemotingProtocolVersion      2.2

Ran the command below, which seemed to complete just fine...
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

Re-ran one of the install-module commands again, and got the below error...
PS C:\scripts> install-module -name MSOnline -force -allowclobber
install-module : The term 'install-module' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
At line:1 char:1
+ install-module -name MSOnline -force -allowclobber
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (install-module:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by NoMoreFood** [comment]
Try upgrading: https://www.microsoft.com/en-us/download/details.aspx?id=54616

**Comment by DudeLooksLikeASupportTech** [comment]
Upgraded yesterday before going home, and scheduled a reboot of the server overnight.  This morning confirmed that the PSVersion is v5.1.

Ran the command below in an admin-level PS shell, and got the included output...
_PS C:\scripts>  install-module -name MSOnline -force

NuGet provider is required to continue
PowerShellGet requires NuGet provider version '2.8.5.201' or newer to interact with NuGet-based repositories. The NuGet
 provider must be available in 'C:\Program Files\PackageManagement\ProviderAssemblies' or
'C:\Users\netfrank.KISH\AppData\Local\PackageManagement\ProviderAssemblies'. You can also install the NuGet provider by
 running 'Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force'. Do you want PowerShellGet to install
and import the NuGet provider now?
[Y] Yes  [N] No  [S] Suspend  [?] Help (default is "Y"):
WARNING: Unable to download from URI 'https://go.microsoft.com/fwlink/?LinkID=627338&clcid=0x409' to ''.
WARNING: Unable to download the list of available providers. Check your internet connection.
PackageManagement\Install-PackageProvider : No match was found for the specified search criteria for the provider
'NuGet'. The package provider requires 'PackageManagement' and 'Provider' tags. Please check if the specified package
has the tags.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:7405 char:21_

I put the failed url into a web browser (https://go.microsoft.com/fwlink/?LinkID=627338&clcid=0x409) , and it seemed to retrieve it just fine...
<?xml version="1.0" encoding="utf-8"?>
<SoftwareIdentity xmlns="http://standards.iso.org/iso/19770/-2/2015/schema.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:discovery="http://packagemanagement.org/discovery" patch="false" media="(OS:windows)" name="OneGet.Providers" tagVersion="1" uniqueId="OneGet.Providers.1" version="1.15.194.0" versionScheme="multipartnumeric">

    

     <Link href="https://onegetcdn.azureedge.net/providers/nuget-2.8.5.208.package.swidtag" type="application/swid-tag+xml" rel="package" discovery:name="nuget" discovery:latest="true" discovery:version="2.8.5.208" media="(OS:windows)" />

   <Link href="https://onegetcdn.azureedge.net/providers/psl-1.0.0.210.package.swidtag" type="application/swid-tag+xml" rel="package" discovery:name="psl" discovery:latest="true" discovery:version="1.0.0.210" media="(OS:windows)" />
  
    <Link href="https://onegetcdn.azureedge.net/providers/ChocolateyPrototype-2.8.5.130.package.swidtag" type="application/swid-tag+xml" rel="package" discovery:name="chocolatey" discovery:latest="true" discovery:version="2.8.5.130" media="(OS:windows)" />

    <Link href="https://onegetcdn.azureedge.net/providers/nugetv2.feed.swidtag" type="application/swid-tag+xml" rel="feed" discovery:name="nuget" media="(OS:windows)" />

    <Link href="https://onegetcdn.azureedge.net/providers/psl.feed.swidtag" type="application/swid-tag+xml" rel="feed" discovery:name="nuget" media="(OS:windows)" />

    <Link href="https://onegetcdn.azureedge.net/providers/chocolateyprototype.feed.swidtag" type="application/swid-tag+xml" rel="feed" discovery:name="chocolatey" media="(OS:windows)" />
</SoftwareIdentity>

**Comment by DeemOnSecurity** [comment]
Give this a shot. Based on my googling it appears this is a TLS issue: https://stackoverflow.com/a/61246161

**Comment by DudeLooksLikeASupportTech** [comment]
Yeah, sorry, I found that myself shortly before your answer.  I reran the command below, which made everything start working...
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

Thanks for the help everyone.  Every time I have to deal with powershell I remember why no one does it unless they have to.  It always ends in having to fix 15 other problems just to get one script to run.
