### ISSUE TITLE
Update PowerShell module load

### ISSUE THREAD

**Issue by DataGuys** [cisagov/Sparrow#11]
# 🚀 Feature Proposal

PowerShell modules on Windows 10 do not load properly the first run and PowerShell needs to be run as administrator for those modules to install properly.

## Motivation

Cleaner way to get this going and run the script direct from the raw Github content for security.

## Example

Install-Module CloudConnect -AllowClobber
Install-Module AzureAD -AllowClobber
Install-Module MSOnline -AllowClobber

Import-Module CloudConnect -Global
Import-Module AzureAD -Global
Import-Module MSOnline -Global

Set-Location $env:USERPROFILE\desktop
$SparrowGitHub = Invoke-WebRequest "https://raw.githubusercontent.com/cisagov/Sparrow/develop/Sparrow.ps1"
Invoke-Expression $($SparrowGitHub.Content)

## Pitch

Why does this feature belong in this project?

**Comment by DeemOnSecurity** [comment]
Upon further discussion, this is not a change we will implement.
