### ISSUE TITLE
$ExportDir not used for export

### ISSUE THREAD

**Issue by Willmage12** [cisagov/Sparrow#12]
Not sure if it's been mentioned yet. I haven't run the script yet as I'm waiting on the permissions to be provisioned, but looking over the script I noticed the $ExportDir variable that can be changed to wherever the user prefers their exports/output to go, but it seems if a user were to want to change this, it wouldn't have any effect:

Line 22:
    $ExportDir = "$home\Desktop\ExportDir"
    If (!(Test-Path $ExportDir)){
        New-Item -Path $ExportDir -ItemType "Directory" -Force
    }

Line 358
        If ($AppendType -eq "Append"){
            $DataArr | Export-csv $home\Desktop\ExportDir\$CsvName.csv -NoTypeInformation -Append
        } Else {
            $DataArr | Export-csv $home\Desktop\ExportDir\$CsvName.csv -NoTypeInformation
        }

I'd imagine you would want this to be something more like:

        If ($AppendType -eq "Append"){
            $DataArr | Export-csv $ExportDir\$CsvName.csv -NoTypeInformation -Append
        } Else {
            $DataArr | Export-csv $ExportDir\$CsvName.csv -NoTypeInformation
        }

**Comment by NoMoreFood** [comment]
Already addressed in my pull request: https://github.com/cisagov/Sparrow/pull/8  Download here if interested https://github.com/NoMoreFood/Sparrow
