### ISSUE TITLE
Change parameter value 

### ISSUE THREAD

**Issue by fmigacz-zz** [cisagov/Sparrow#14]
# 🚀 Feature Proposal

In Export-UALData function, change "Sharepoint" value of -WorkloadType parameter to "SharePoint"
* function call/parameter passing on line 143
* use of parameter value on line 324 

## Motivation

"Sharepoint" is an incorrect capitalization of the service. A PR was raised to fix this in the comments (#13), but the repo owners should make sure any parameter value changes have no additional effect.

## Example

Minor typographical change.

## Pitch

This is only to correctly identify the queried service in Microsoft M365.

**Comment by DeemOnSecurity** [comment]
Thank you. We will address this when we merge pull request #8
