### ISSUE TITLE
What is the default directory where the csv-files should appear?  

### ISSUE THREAD

**Issue by PepeLePew54** [cisagov/Sparrow#16]
# 💬 Questions and Help

Currently able to run  the script successfully, but can't get any csv-files anywhere?

**Comment by DeemOnSecurity** [comment]
The current version of Sparrow.ps1 drops the csv files in the user's $Home\Desktop\ExportDir\\\<collection\>.csv

**Comment by PepeLePew54** [comment]
Thanks for quick reply!

**Comment by DeemOnSecurity** [comment]
Of course. Please let us know if this resolves your issue.

> We have pushed a new version of Sparrow.ps1 which lets you select the output dir if that's helpful
