### ISSUE TITLE
Warning; Excel not found - skipping combined file.

### ISSUE THREAD

**Issue by AK47Brown** [cisagov/Sparrow#19]
# 🐛 Bug Report

Getting this error "Warning; Excel not found - skipping combined file." once the script is finished running

## To Reproduce

- Just run the script using defaults

## Expected behavior

I suppose all the separate .CSV files would be merged. I have Excel so I'm not sure why it's saying not found.

**Comment by DeemOnSecurity** [comment]
The application checks if you have excel by calling:

```powershell
$Excel = New-Object -ComObject Excel.Application
```

If you run this in your PowerShell terminal, it may reveal why you're getting this message.

**Comment by AK47Brown** [comment]
Ok thanks.... This is taking me down a DCOM permission rabbit hole so this bug report can be closed as being a user issue.
