### ISSUE TITLE
Files in ExportDir

### ISSUE THREAD

**Issue by ncoimbra** [cisagov/Sparrow#21]
After finish the script and creating the files, all these files was empty. Can be user permissions? The user are Global Admin. Thanks.

**Comment by genericdevname** [comment]
Are you running the most current version of Sparrow? Are there any errors that show up when you run the script?

When you say all the files, do you mean every single CSV was empty (including Domain_List.csv and ApplicationGraphPermissions)?

If you mean only the CSVs from Get-UALData, please try the following.

Connect to Exchange Online via PowerShell and run the following code in PowerShell:

```
[datetime] $StartDate = [DateTime]::UtcNow.AddYears(-1).AddMinutes(10)
[datetime] $EndDate = [DateTime]::UtcNow

$PSLoginData1 = Search-UnifiedAuditLog -StartDate $StartDate -EndDate $EndDate -ResultSize 5000  -FreeText "a0c73c16-a7e3-4564-9a95-2bdf47383716"

$PSLoginData1 
```

If you don't return results from the above code, keep trying different calls. If none of the functions return a value, try:

`Search-UnifiedAuditLog -StartDate $StartDate -EndDate $EndDate -ResultSize 5000`

Does the above snippet return results?

Please let us know if you are still running into issues!

**Comment by genericdevname** [comment]
I wanted to follow up and make sure that you were able to resolve the issue--looking to close this issue at the end of the day, if no response is given.

**Comment by ncoimbra** [comment]
It's weird, I left my answer last week and now I can't see it ... Those commands don't return any results ... The Sparrow version used was the one that was published when I made my first bug comment. I just re-run the script (which I see was modified 3hs ago) and it ran without problems ... You can close this issue. Thanks.

**Comment by DeemOnSecurity** [comment]
> It's weird, I left my answer last week and now I can't see it ... Those commands don't return any results ... The Sparrow version used was the one that was published when I made my first bug comment. I just re-run the script (which I see was modified 3hs ago) and it ran without problems ... You can close this issue. Thanks.

@ncoimbra Happy it worked! Thank you for raising the issue!
