### ISSUE TITLE
Script fails to fetch audit logs

### ISSUE THREAD

**Issue by thereverand** [cisagov/Sparrow#22]
```
Audit log search argument startDate should be after 1/4/2020 1:02:22 PM UTC.
    + CategoryInfo          : InvalidArgument: (:) [Search-UnifiedAuditLog], ArgumentException
    + FullyQualifiedErrorId : [Server=BL0PR12MB4674,RequestId=e9594a36-7cf9-4f8f-b740-6db2782716ec,TimeStamp=1/4/2021
   1:02:22 PM] [FailureCategory=Cmdlet-ArgumentException] F788A15A,Microsoft.Exchange.Management.SystemConfigurationT
  asks.SearchUnifiedAuditLog
    + PSComputerName        : outlook.office365.com
```
It's trying to get more than 1 year of logs, which will never work.

**Comment by jvalente-salemstate** [comment]
What I think happens is that they accounted for the script not allowing queries over a year, but it's set at "1 year minus 10 minutes. If the script takes long enough to run, it eventually starts failing as the start date falls beyond that 10 minute window.
I had to work around by changing AddYears(-1) to AddDays(-364). I lose a bit of logs but it works better.

**Comment by markgordon03** [comment]
I found similar behavior, though elected for a slightly different solution.  You can use [DateTime]::UtcNow.AddYears(-1).AddHours(1) or [DateTime]::UtcNow.AddYears(-1).AddMinutes(60) to give the script an hour to run.

**Comment by DeemOnSecurity** [comment]
> I found similar behavior, though elected for a slightly different solution. You can use [DateTime]::UtcNow.AddYears(-1).AddHours(1) or [DateTime]::UtcNow.AddYears(-1).AddMinutes(60) to give the script an hour to run.

Do you want to submit a pull with this modification and we'll merge?
