### ISSUE TITLE
Choose your Azure Environment prompt does not proceed

### ISSUE THREAD

**Issue by NotaDevToday** [cisagov/Sparrow#23]
# 🐛 Bug Report

The script prompts to choose my Azure environment, but does not proceed when entering "AzureCloud", tenant ID or any other options. 

## To Reproduce

The script ran until loading "Microsoft.Online.Identity.Federation.PowerShell.dll" which failed.  I have Security Admin role in AzureAD. 

## Expected behavior

Readme did not list acceptable input. 

## Any helpful log output

Paste the results here:

```bash

```

**Comment by DeemOnSecurity** [comment]
I am unable to replicate this issue. You have confirmed **all** permissions outlined in [README.md](/cisagov/Sparrow/blob/develop/README.md) are allocated?

**Comment by TyNavarre** [comment]
I was having the same issue. Looking at the permission confirmation, and realizing that in my local PowerShell session I had yet to authenticate against Azure/365, I ran, "Connect-AzureAD" and signed in with my Azure admin account. After that I re-ran the script and it worked.

**Comment by NotaDevToday** [comment]
> I was having the same issue. Looking at the permission confirmation, and realizing that in my local PowerShell session I had yet to authenticate against Azure/365, I ran, "Connect-AzureAD" and signed in with my Azure admin account. After that I re-ran the script and it worked.

You're absolutely right.  I was trying to use Connect-AzAccount instead.  The script is running now.  Thank you!
