### ISSUE TITLE
 The HTTP error (12175) is: A security error occurred .

### ISSUE THREAD

**Issue by musharsec** [cisagov/Sparrow#25]
For more information, see the about_Remote_Troubleshooting Help topic..
 
 Have troubleshooted but unable to identify the issue - permissions are set and able to run other commands. gets to around 400 get-requests then errors

Import-PSSession : Running the Get-Command command in a remote session reported the following error: Processing data
for a remote command failed with the following error message: WS-Management cannot process the request. The operation
failed because of an HTTP error. The HTTP error (12175) is: A security error occurred . For more information, see the
about_Remote_Troubleshooting Help topic..
At C:\Program Files\WindowsPowerShell\Modules\ExchangeOnlineManagement\2.0.3\ExchangeOnlineManagement.psm1:435 char:40
+ ... oduleInfo = Import-PSSession $PSSession -AllowClobber -DisableNameChe ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidResult: (:) [Import-PSSession], RuntimeException
    + FullyQualifiedErrorId : ErrorFromRemoteCommand,Microsoft.PowerShell.Commands.ImportPSSessionCommand

**Comment by DeemOnSecurity** [comment]
This error is likely due to permissions or TLS. Please confirm all permissions outlined in the README are allocated and that your Windows machine is properly configured to use TLS 1.2 [(This may help)](https://support.microsoft.com/en-us/help/3140245/update-to-enable-tls-1-1-and-tls-1-2-as-default-secure-protocols-in-wi#easy).

**Comment by DeemOnSecurity** [comment]
Pinging again to ensure there is no longer an issue, will close the pull at the end of the week if nothing heard.
