### ISSUE TITLE
Exchange Online Access denied

### ISSUE THREAD

**Issue by hugo320** [cisagov/Sparrow#28]
I met below error while running this script, and would like to know do you have any guidance on how to run this script in steps.

New-ExoPSSession : Connecting to remote server partner.outlook.cn failed with the following error message : Access is
denied. For more information, see the about_Remote_Troubleshooting Help topic.
At C:\Program Files\WindowsPowerShell\Modules\ExchangeOnlineManagement\2.0.3\ExchangeOnlineManagement.psm1:426 char:30
+ ... PSSession = New-ExoPSSession -ExchangeEnvironmentName $ExchangeEnviro ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [New-ExoPSSession], PSRemotingTransportException
    + FullyQualifiedErrorId : System.Management.Automation.Remoting.PSRemotingDataStructureException,Microsoft.Exchang
   e.Management.ExoPowershellSnapin.NewExoPSSession

**Comment by DeemOnSecurity** [comment]
It appears to be a permission issue, see [this](https://docs.microsoft.com/en-us/exchange/troubleshoot/administration/access-denied-connect-powershell) article.

**Comment by DeemOnSecurity** [comment]
Pinging to make sure you were able to resolve! Going to close at the end of the week if nothing is heard.
