### ISSUE TITLE
Azure Tenants without 0365 Email script failure

### ISSUE THREAD

**Issue by dvp420** [cisagov/Sparrow#29]
# 🐛 Summary #

On domains with Azure tenants, that are not leveraging 0365 for email, there is not a 'null' choice for the 0365 option which causes the PowerShell Exchange module to not find the 0365 tenant and errors with:

New-ExoPSSession : AADSTS500014: The service principal for resource 'https://outlook.office365.com' is disabled.  This indicate that a subscription within the tenant has lapsed, or that the administrator for this tenant has disabled the application, preventing tokens from being issued for it.

This occurs prior to being asked for the license type (of which there is no license type)

## To reproduce ##

1. Identify or create an Azure tenant without 0365 email.
2. Create a user with adequate Azure permissions per instructions. No ability to create this user with required 0365 email permissions OR use an Azure Global Administrator (not recommended).
3. Run .\sparrow.ps1 as Powershell Admin

## Expected behavior ##

Hoping the expected behavior would allow me to skip the Exchange portion of the analysis but still provide analysis of anything found in Azure tenant.

## Any helpful log output or screenshots ##

Paste the results here:

```console

```

Add any screenshots of the problem here.
![image](https://user-images.githubusercontent.com/77017087/103675565-15fede00-4f4e-11eb-9b0a-6e24b4060e11.png)

**Comment by DeemOnSecurity** [comment]
Interesting, perhaps we need to add a switch to disable the O365 check

**Comment by genericdevname** [comment]
Maybe I'm misreading the issue, but what if you comment out line 475:
`
Get-UALData -ExportDir $ExportDir -StartDate $StartDate -EndDate $EndDate -ExchangeEnvironment $ExchangeEnvironment -AzureEnvironment $AzureEnvironment -Verbose`

Do you still receive the error?

**Comment by dvp420** [comment]
I don't think you're misreading the issue. I commented line 475 and re-ran and got the export files successfully generated. I had attempted to identify which line(s) would be required...but #notadev. Thanks! I still think it would be an improvement to have a switch but simply adding this to the documentation would also be sufficient. I'm closing the issue.

**Comment by dvp420** [comment]
Perhaps I closed too soon without verifying what the output results should be after commenting out 475. In my scenario, I only got two .csv files. ApplicationGraphPermissions.csv and Domain_list.csv.

What I don't have, and perhaps it's a good sign, is that there's no files for AppRoleAssignment_Operations_Export.csv, AppUpdate_Operations_Export.csv, Consent_Operations_Export.csv, Domain_Operations_Export.csv,PSLogin_Operations_Export.csv,SAMLToken_Operations_Export.csv,ServicePrincipal_Operations_Export.csv

**Comment by genericdevname** [comment]
Thank you for clarifying. Sparrow relies on being able to look at the unified audit log of a tenant organization, which is part of the Exchange Online PowerShell cmdlets (https://docs.microsoft.com/en-us/powershell/module/exchange/search-unifiedauditlog?view=exchange-ps).

Without Exchange Online, you will only receive those two .csv files.

**Comment by dvp420** [comment]
Thanks for the clarification. And those two files are pretty benign in what they're going to show. the UAL stuff is really where the IOC or other unknown activities to be investigated would be.
