### ISSUE TITLE
Switch to ExchangeOnlineManagement

### ISSUE THREAD

**Issue by stevenffrench** [cisagov/Sparrow#3]
Please switch to using the ExchangeOnlineManagement module instead of CloudConnect for connecting to Exchange Online.

The ExchangeOnlineManagement module is the officially supported way to connect to Exchange Online.  The actual implemention is just a few small code updates

**Comment by NoMoreFood** [comment]
Agreed on this. I had to adapt the script for ExchangeOnlineManagement in order to support our MFA requirements.
