### ISSUE TITLE
PowerShell script fails with error: Unable to get the delete property of the worksheet class

### ISSUE THREAD

**Issue by Vaeldas** [cisagov/Sparrow#30]
# 🐛 Summary #

What's wrong? Please be specific.

## To reproduce ##

1) Run the Script
2) Fails after being asked for AzureCloud Credentials two times

## Expected behavior ##

The script to finish without error

## Any helpful log output or screenshots ##

Paste the results here:

```console

```

Add any screenshots of the problem here.

<img width="802" alt="Screen Shot 2021-01-05 at 12 11 31 PM" src="https://user-images.githubusercontent.com/77019927/103683389-c0c3cc00-4f4f-11eb-8afd-f3934b721b9b.png">

**Comment by DeemOnSecurity** [comment]
Oof, this appears to be an odd issue with [Workbooks in Powershell](https://stackoverflow.com/questions/39859276/comexception-when-trying-to-delete-a-worksheet-from-an-excel-file-in-c-sharp). We will work on a fix.

For your own immediate analysis, this step is after the .csv files are created, so you should be able to find them in your output directory.

**Comment by d13g0s0uz4** [comment]
Same issue here. CSV files were generated successfully

**Comment by DeemOnSecurity** [comment]
This appears to be an issue with older versions of excel, we're sending up a pull request now to fix this.
