### ISSUE TITLE
Script returns nothing

### ISSUE THREAD

**Issue by kristyacevedo** [cisagov/Sparrow#35]
Do you have to have E5 license in order for this script to work?  We have E1 and the script does not create an output file.  Nothing happens when finished.

**Comment by DeemOnSecurity** [comment]
To confirm, there is nothing in the output directory? (Defaults to $CurrentUser\Desktop\ExportDir) 

The license question is only for MailItems_Operations_Export.csv

**Comment by kristyacevedo** [comment]
Okay, got it.  thank you!

**Comment by DeemOnSecurity** [comment]
No problem! Happy hunting!
