### ISSUE TITLE
Unable to get the SaveAs property of the Workbook class

### ISSUE THREAD

**Issue by apollogd** [cisagov/Sparrow#37]
Unable to get the SaveAs property of the Workbook class
At C:\support\Sparrow.ps1:113 char:5
+     $Workbook.SaveAs((Join-Path $ExportDir 'Summary_Export.xlsx'))
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], COMException
    + FullyQualifiedErrorId : System.Runtime.InteropServices.COMException

**Comment by DeemOnSecurity** [comment]
What is your Excel and Powershell version?

**Comment by apollogd** [comment]
Powershell version is 5.1.18362.752
Excel Version is Excel for Office365 MSO 16.0.12026.20344

Thx.

**Comment by lindaorny** [comment]
Same issue here with powershell version as 5.1.18362.752 and excel version is MS Office Home and Business 2013 15.0.5259.1000

**Comment by mbuchanan1229** [comment]
Same issue

Unable to get the SaveAs property of the Workbook class
At line:113 char:5
+     $Workbook.SaveAs((Join-Path $ExportDir 'Summary_Export.xlsx'))
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], COMException
    + FullyQualifiedErrorId : System.Runtime.InteropServices.COMException

Office 365 A3

PS C:\WINDOWS\system32> Get-Host | Select-Object Version

Version      
-------      
5.1.19041.610

Windows 10

**Comment by A1m33** [comment]
Same issue here with PowerShell 5.1.17763.1490,  Excel O365 16.0.10730.20438, on Win 10.

```
Unable to get the SaveAs property of the Workbook class
+     $Workbook.SaveAs((Join-Path $ExportDir 'Summary_Export.xlsx'))
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : OperationStopped: (:) [], COMException
+ FullyQualifiedErrorId : System.Runtime.InteropServices.COMException
```

**Comment by cr45hmurphy** [comment]
Same issue.

```
Powershell Version
-------
5.1.17134.858

Excel Version
--------
16.0.9126.2336 64-bit

```

**Comment by dlucey1818** [comment]
Same issue:
Powershell Version
-------
5.1.18362.1171

Excel Version
16.0.11231.20164

**Comment by cr45hmurphy** [comment]
Has there been any movement on this issue?

**Comment by akheva** [comment]
Currently having the same issue.

PSVersion                      5.1.19041.610
Excel 2019                     16.0.10346.20002

**Comment by genericdevname** [comment]
I added a fix with the newest pull request, can you please test to see if that fixes the issue?

**Comment by mbuchanan1229** [comment]
Working for me



[cid:image001.png@01D6FF82.44EB48F0]Call me on Teams<https://teams.microsoft.com/l/call/0/0?users=buchananm@delawareareacc.org>
Mitchell Buchanan
Systems Administrator
Delaware Area Career Center
4565 Columbus Pike
Delaware, OH  43015
ph: (740) 203-2252
fax: (740) 549-1397
www.DelawareAreaCC.org<http://www.delawareareacc.org/>


[A picture containing food  Description automatically generated]

Empower. Prepare. Inspire. Connect.
Elevate your life.

[A picture containing object, drawing  Description automatically generated]<https://www.facebook.com/DelawareAreaCC/> [A close up of a sign  Description automatically generated] <https://twitter.com/DelawareAreaCC>   [A close up of a logo  Description automatically generated] <https://www.instagram.com/delawareareacc/>   [A picture containing drawing  Description automatically generated] <https://www.linkedin.com/school/delaware-area-career-center>   [A picture containing drawing  Description automatically generated] <https://www.youtube.com/channel/UCfa-oXG2AnxyeW0UR7zPD7A/videos>

Confidentiality Notice: This e-mail message, from Delaware Area Career Center, Delaware, Ohio, including any attachments, is for the sole use of the intended recipient(s) and may contain information that is privileged, confidential and/or exempt from disclosure under applicable law. If you are not the intended recipient or authorized to receive information for the recipient, you are hereby notified that any review, use, disclosure, distribution, copying, printing, or action taken in reliance on the contents of this e-mail is strictly prohibited. If you have received this communication in error, please immediately contact the sender and destroy the material in its entirety.

**Comment by cr45hmurphy** [comment]
Issue is still occurring. Pulled from repo today. Still receiving the error.

![image](https://user-images.githubusercontent.com/4840152/107677547-00bd5380-6c60-11eb-87f1-cba8729c363e.png)

**Comment by genericdevname** [comment]
> Issue is still occurring. Pulled from repo today. Still receiving the error.
> 
> ![image](https://user-images.githubusercontent.com/4840152/107677547-00bd5380-6c60-11eb-87f1-cba8729c363e.png)

I'll make a new pull request to address this continuing issue.

**Comment by genericdevname** [comment]
Merged a pull request, please try re-running Sparrow and let me know if that resolves the issue.

**Comment by cr45hmurphy** [comment]
> 
> 
> Merged a pull request, please try re-running Sparrow and let me know if that resolves the issue.

Testing it now.

**Comment by cr45hmurphy** [comment]
@genericdevname it appears that the Try-Catch worked like a charm. The script completed. No CSVs were produced, though it says that that is the case if nothing matched the search criteria. 

Question: It says that CSVs will remain in the default export directory. Would this be the same directory as the script?

**Comment by genericdevname** [comment]
The CSVS are exported to the user's default home directory in a folder called 'ExportDir' (ie: Desktop/ExportDir).

Also, there are messages throughout the script that state if there is no data returned, it will not produce a CSV as well.  If you see those messages, the CSVs will not be produced.

**Comment by cr45hmurphy** [comment]
> 
> 
> The CSVS are exported to the user's default home directory in a folder called 'ExportDir' (ie: Desktop/ExportDir).
> 
> Also, there are messages throughout the script that state if there is no data returned, it will not produce a CSV as well. If you see those messages, the CSVs will not be produced.

Rock on! Didn't even realize that directory was created.

Also, thank you for confirming that for me. I knew it was saying that a CSV wouldn't be created, but I wasn't sure if an "End of Scan" report would be generated or not.

Thank you for the help on this issue!
