### ISSUE TITLE
Unable to get the SaveAs property of the Workbook class

### ISSUE THREAD

**Issue by johnpbarrus** [cisagov/Sparrow#38]
# 🐛 Summary #

At \Sparrow.ps1:113 char:5
+     $Workbook.SaveAs((Join-Path $ExportDir 'Summary_Export.xlsx'))
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], COMException
    + FullyQualifiedErrorId : System.Runtime.InteropServices.COMException

**Comment by DeemOnSecurity** [comment]
#37 Duplicate issue, closing
