### ISSUE TITLE
Could not load type 'Syste.Security.Cryptography.SHA256Cng'

### ISSUE THREAD

**Issue by bhecit** [cisagov/Sparrow#39]
Running sparrow command on Server 2012 R2 domain joined server from an acount with full Azure admin rights; Powershell 7.1, all needed modules installed, and getting this error:

![PSerr2](https://user-images.githubusercontent.com/39417155/103814717-68f49600-501f-11eb-88e8-9e8ccca7dd22.PNG)

Could not load type 'Syste.Security.Cryptography.SHA256Cng' from assembly 'System.core, Version=4.0.0.0, Culture=neutral, PublicKeyToken =

I have no idea idea what this means; found some references to it online from other users doing unrelated projects but no answer; not sure if this is PS malfunction or a permissions error. Any advice?

**Comment by genericdevname** [comment]
Can you try using a lower version of PowerShell?

EDIT: Lower version like PowerShell 5.1

**Comment by genericdevname** [comment]
Hello, we have not heard back from you regarding this issue.  If no response is given within three days, I will go ahead and close out this issue.
