### ISSUE TITLE
Getting an I/O operation error 

### ISSUE THREAD

**Issue by pramodpabbati** [cisagov/Sparrow#40]
# 🐛 Summary #

I am getting an I/O operation error on running the script. This is after we input our choice of Azure and O365 environments. Prior to getting this error, I had just fixed an issue with TLS 1.2 communications.

Starting a command on the remote server failed with the following error message : The I/O operation has been aborted because of
either a thread exit or an application request. For more information, see the about_Remote_Troubleshooting Help topic.
    + CategoryInfo          : OperationStopped: (outlook.office365.com:String) [], PSRemotingTransportException
    + FullyQualifiedErrorId : JobFailure
    + PSComputerName        : outlook.office365.com

![cisasparrowerr](https://user-images.githubusercontent.com/29285512/103915448-3ad38c80-50d9-11eb-8e6a-ce1774a2ca66.jpg)

**Comment by genericdevname** [comment]
Did you restart the computer after fixing the TLS 1.2 issue? 

If not, can you try doing that and re-running the script? If it still continues, please make sure your WinRM service is running by running this cmdlet in an administrator PowerShell window: `Start-Service WinRM`

**Comment by pramodpabbati** [comment]
Restart worked and running the WinRM service worked! You can close this report. Thank you!

**Comment by pramodpabbati** [comment]
My Apologies. Although I see some logs in the ~\ExportDir\ looks like some of the modules failed. Here are the details:

Starting a command on the remote server failed with the following error message : The I/O operation has been aborted
because of either a thread exit or an application request. For more information, see the about_Remote_Troubleshooting
Help topic.
    + CategoryInfo          : OperationStopped: (outlook.office365.com:String) [], PSRemotingTransportException
    + FullyQualifiedErrorId : JobFailure
    + PSComputerName        : outlook.office365.com


Audit log search argument startDate should be after 1/7/2020 8:43:38 PM UTC.
    + CategoryInfo          : InvalidArgument: (:) [Search-UnifiedAuditLog], ArgumentException
    + FullyQualifiedErrorId : [Server=XXXXXXXXXXXXXX,RequestId=0846ce0c-ac5b-405c-a86e-1385c063f9af,TimeStamp=1/7/202
   1 8:43:39 PM] [FailureCategory=Cmdlet-ArgumentException] F5DF40F7,Microsoft.Exchange.Management.SystemConfiguratio
  nTasks.SearchUnifiedAuditLog
    + PSComputerName        : outlook.office365.com

<img width="943" alt="cisasparrowerr1 jpg" src="https://user-images.githubusercontent.com/29285512/103944235-5783ba80-5101-11eb-8a26-a1cc7b48cef6.png">

**Comment by genericdevname** [comment]
For the I/O issue, please read https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_remote_troubleshooting to see if any other scenario is applicable.

For the StartDate issue, please download the latest Sparrow or ensure that your StartDate variable is set to the following value:

```
    [Parameter()]
    [datetime] $StartDate = [DateTime]::UtcNow.AddDays(-364),
```
