### ISSUE TITLE
Issues found after executing script

### ISSUE THREAD

**Issue by nriveras4** [cisagov/Sparrow#41]
At C:\Admin\Crowdstrike Tool\Get-CRTReport.ps1:168 char:21
+                 Sign&nbsp;up
+                     ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quotation marks ("&") to pass it as part of a string.
At C:\Admin\Crowdstrike Tool\Get-CRTReport.ps1:195 char:190
+ ... ata-ga-click="(Logged out) Header, go to Features">Features <span cla ...
+                                                                 ~
The '<' operator is reserved for future use.
At C:\Admin\Crowdstrike Tool\Get-CRTReport.ps1:195 char:261
+ ... ="Bump-link-symbol float-right text-normal text-gray-light">&rarr;</s ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quotation marks ("&") to pass it as part of a string.
At C:\Admin\Crowdstrike Tool\Get-CRTReport.ps1:209 char:255
+ ... ogged out) Header, go to Customer stories">Customer stories <span cla ...
+                                                                 ~
The '<' operator is reserved for future use.
At C:\Admin\Crowdstrike Tool\Get-CRTReport.ps1:209 char:326
+ ... ="Bump-link-symbol float-right text-normal text-gray-light">&rarr;</s ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quotation marks ("&") to pass it as part of a string.
At C:\Admin\Crowdstrike Tool\Get-CRTReport.ps1:210 char:231
+ ... ata-ga-click="(Logged out) Header, go to Security">Security <span cla ...
+                                                                 ~
The '<' operator is reserved for future use.
At C:\Admin\Crowdstrike Tool\Get-CRTReport.ps1:210 char:302
+ ... ="Bump-link-symbol float-right text-normal text-gray-light">&rarr;</s ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quotation marks ("&") to pass it as part of a string.
At C:\Admin\Crowdstrike Tool\Get-CRTReport.ps1:233 char:222
+ ... a-click="(Logged out) Header, go to Explore">Explore GitHub <span cla ...
+                                                                 ~
The '<' operator is reserved for future use.
At C:\Admin\Crowdstrike Tool\Get-CRTReport.ps1:233 char:293
+ ... ="Bump-link-symbol float-right text-normal text-gray-light">&rarr;</s ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quotation marks ("&") to pass it as part of a string.
At C:\Admin\Crowdstrike Tool\Get-CRTReport.ps1:236 char:107
+ ...  text-normal text-mono f5 mb-2 border-lg-top pt-lg-3">Learn &amp; con ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quotation marks ("&") to pass it as part of a string.
Not all parse errors were reported.  Correct the reported errors and try again.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : AmpersandNotAllowed

**Comment by DeemOnSecurity** [comment]
It appears this issue has been posted in the wrong repository.

**Comment by genericdevname** [comment]
This doesn't look like the Sparrow script, will be closing this issue.
