### ISSUE TITLE
cmdlet error

### ISSUE THREAD

**Issue by betheball** [cisagov/Sparrow#43]
# 🐛 Summary #

I am getting the following erros

Do you have an Office 365/Microsoft 365 E5/G5 license? Y/N: N
Would you like to investigate a certain application? Y/N: N
Skipping AppID investigation

VERBOSE: Searching for 'Set domain authentication' and 'Set federation settings on domain' operations in the
 UAL.
Search-UnifiedAuditLog : The term 'Search-UnifiedAuditLog' is not recognized as the name of a cmdlet,
function, script file, or operable program. Check the spelling of the name, or if a path was included,
verify that the path is correct and try again.
At C:\Windows\system32\Sparrow.ps1:154 char:19
+     $DomainData = Search-UnifiedAuditLog -StartDate $StartDate -EndDa ...
+                   ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Search-UnifiedAuditLog:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

VERBOSE: Searching for 'Update application' and 'Update application ? Certificates and secrets management'
in the UAL.
Search-UnifiedAuditLog : The term 'Search-UnifiedAuditLog' is not recognized as the name of a cmdlet,
function, script file, or operable program. Check the spelling of the name, or if a path was included,
verify that the path is correct and try again.
At C:\Windows\system32\Sparrow.ps1:161 char:16
+     $AppData = Search-UnifiedAuditLog -StartDate $StartDate -EndDate  ...
+                ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Search-UnifiedAuditLog:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by mpeck12** [comment]
I am having this same problem. 

Calling "Connect-ExchangeOnline" in PowerShell before running Sparrow.ps1 seems to fix it. 

A call to Connect-ExchangeOnline may need to be added to Sparrow.ps1?

**Comment by DeemOnSecurity** [comment]
Can you test this fix and see if it works @betheball?

**Comment by genericdevname** [comment]
Hello, we have not heard back from you regarding this issue. If no response is given within three days, I will go ahead and close out this issue.

**Comment by mkrishna771** [comment]
I'm also facing the same issue. pls advise fixing the issue
![image](https://user-images.githubusercontent.com/77604296/104877795-a858a600-5980-11eb-9ff2-772f79d8e728.png)

**Comment by genericdevname** [comment]
@mkrishna771 Can you try running `Connect-ExchangeOnline` and then running Sparrow?

**Comment by genericdevname** [comment]
Hello, we have not heard back from you regarding this issue. If no response is given within three days, I will go ahead and close out this issue.
