### ISSUE TITLE
Document requirement to turn on Unified Audit Log before using Sparrow

### ISSUE THREAD

**Issue by mpeck12** [cisagov/Sparrow#46]
The Unified Audit Log must be activated before using Sparrow - this requirement should be documented
(and if possible, Sparrow should warn the user at runtime if the Unified Audit Log hasn't been activated?):

- Requires an Office 365 license (E5 license?)

- Need to go to https://protection.office.com , click Search -> Audit Log Search and click Turn On Auditing. May take 24 hours for auditing to fully activate.

**Comment by genericdevname** [comment]
Added documentation in the readme: `Unified Audit Logs will need to be enabled.`

However, users should ensure that the UAL is turned on prior to running Sparrow.
