### ISSUE TITLE
Automated Execution (Scheduled Task)

### ISSUE THREAD

**Issue by jh2007** [cisagov/Sparrow#47]
Is it possible to execute this script as a scheduled task or is that not recommended? I noticed when running for the first time I am prompted for input so perhaps a scheduled task is not possible. If that is the case, does anyone have any suggestions for automating the execution via an alternate method?

Thanks

**Comment by genericdevname** [comment]
We are currently looking into this request.

**Comment by genericdevname** [comment]
At the moment, this script isn't really meant for being executed as a scheduled task as it has inputs and currently prompts for credentials.
