### ISSUE TITLE
Unable to find type error

### ISSUE THREAD

**Issue by HumanHack** [cisagov/Sparrow#48]
# 🐛 Summary #

when running sparrow.ps1 after issuing connect-exchangeonline, we receive the below error:

Unable to find type [Microsoft.Open.Azure.AD.CommonLibrary.AzureEnvironment].
At C:\WINDOWS\system32\Sparrow.ps1:54 char:26
+ ... ironments = [Microsoft.Open.Azure.AD.CommonLibrary.AzureEnvironment]: ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Open....zureEnvironment:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound
 
Azure Environments
------------------

Choose your Azure Environment [AzureCloud]: 

## To reproduce ##

in powershell execute:
Connect-ExchangeOnline
login in with tenant admin that has required permissions
run: Invoke-WebRequest 'https://github.com/cisagov/Sparrow/raw/develop/Sparrow.ps1' -OutFile 'Sparrow.ps1' -UseBasicParsing; .\Sparrow.ps1

error message as above

## Expected behavior ##

What did you expect to happen that didn't?

## Any helpful log output or screenshots ##

Paste the results here:

```console

```

Add any screenshots of the problem here.

**Comment by genericdevname** [comment]
Do you have the `AzureAD` module installed? If so, what version do you have? If not, can you please install it with the following command: `Install-Module AzureAD`

**Comment by genericdevname** [comment]
Hello, we have not heard back from you regarding this issue. If no response is given within three days, I will go ahead and close out this issue.
