### ISSUE TITLE
Zero KB CSV files after running script. Good or bad?

### ISSUE THREAD

**Issue by amp9020** [cisagov/Sparrow#49]
I ran this script successfully.  It created some files on the desktop but they are ALL 0KB.

What does this mean when 0KB is the result?

SAMLToken_Operations_Export
PSMailbox_Operations_Export
Domain_Operations_Export
AppUpdate_Operations_Export
ServicePrincipal_Operations_Export
AppRoleAssignment_Operations_Export
Consent_Operations_Export

Is this a good outcome?

Also when it asked for a specific application to scan I said NO, 
If i hit yes, it asks for input, but I do not know what parameters are valid.
Does this have any affect when selecting NO for that question?

**Comment by jh2007** [comment]
I also am curious if a null csv file means there was either no data to report or the script failed to obtain the data for some reason? I don't get any errors when executing the script and I assume if there were an issue during execution PowerShell would kick back its glaring red text to let me know.. But I have noticed after running the script that some csv files contain information while others do not.

**Comment by genericdevname** [comment]
Hello, I added some logic to eliminate CSVs that have no data.  If you want, you can try to re-run Sparrow again to see if that resolves some of your questions about the null CSVs.

Please note that zero CSVs can be created by no corresponding data to report, incorrect permissions on the account running Sparrow, or if there was an error running Sparrow/PowerShell.
