### ISSUE TITLE
WorkloadType "AAD" does not include ApplicationId property

### ISSUE THREAD

**Issue by chase-haitch-m** [cisagov/Sparrow#5]
WorkloadType "AAD" does not include the ApplicationId property, though the value is returned within ($_.AuditData | ConvertFrom-Json).ApplicationId

I noticed that the value was missing from the SAMLToken_Operations_Export.csv export.

**Comment by DeemOnSecurity** [comment]
Good morning,

 We are looking into it, apologize for the delay!

**Comment by genericdevname** [comment]
For the SAMLToken_Operations_Export.csv, you can find the same application ID in column X, named Target.
