### ISSUE TITLE
Feature: DeviceCode Login Flag

### ISSUE THREAD

**Issue by nconder** [cisagov/Sparrow#50]
# 💡 Summary #
 Ability to use -DeviceCode for logins

What is the work, as a high-level summary?
Add flag to use -DeviceCode for logins
## Motivation ##

Why does this work belong in this project?
Some orgs use SSO but have vaulted account this can cause login to automatically use SSO login even if another account is entered in the login Window.

This would be useful because...

## Implementation notes ##

Please provide details for implementation, such as:

- an example for how this would be used
Sparrow.ps1 -DeviceCode

## Acceptance criteria ##

How do we know when this work is done?

- [ ] Criterion

**Comment by genericdevname** [comment]
Can you describe in more detail what you are asking for?

**Comment by genericdevname** [comment]
Hello, we have not heard back from you regarding this issue. If no response is given within three days, I will go ahead and close out this issue.
