### ISSUE TITLE
Sparrow script doesn't work under a E3 sub, correct?

### ISSUE THREAD

**Issue by ronni312** [cisagov/Sparrow#51]
I know the documentation states that a E5 subscription is required in order to successfully run the script. Is there any other way to run it or is there less concern with organizations that have a subscription below E5?

**Comment by genericdevname** [comment]
Hello,

In the readme, it states:

> To check for the MailItemsAccessed Operation, your tenant organization requires an Office 365 or Microsoft 365 E5/G5 license.

This means that only the MailItemsAccessed operation will not return data if you don't have an E5/G5 subscription.
