### ISSUE TITLE
Audit Log search error

### ISSUE THREAD

**Issue by yellow-starburst** [cisagov/Sparrow#54]
# 🐛 Summary #

I receive the following error:
`Audit Log search arguement startDate should be after 1/16 12:00 (current date and time)...`

**Comment by genericdevname** [comment]
Can you check to make sure line 7 is set to the following:

`[datetime] $StartDate = [DateTime]::UtcNow.AddDays(-364)`

If it is, you might need to use a lower number such as:

`[datetime] $StartDate = [DateTime]::UtcNow.AddDays(-90)`

Can you please try this and let us know how it works?

**Comment by yellow-starburst** [comment]
Changing the value to 90 days worked.
