### ISSUE TITLE
Choose your Azure Environment [AzureCloud]

### ISSUE THREAD

**Issue by siddeshn** [cisagov/Sparrow#55]
I have multiple subscription and having difficulty in selecting the right subscription.

What should i feed as input ? subscription id ? tenant id ? for the below option

Choose your Azure Environment [AzureCloud]

**Comment by genericdevname** [comment]
If you are using commercial Azure, you can use the default value `AzureCloud` to connect to your tenant.

If you are using Azure US Government, select `AzureUSGovernment`.

**Comment by siddeshn** [comment]
i used AzureCloud . but not working
It's still prompting asking for environment

**Comment by genericdevname** [comment]
Can you post a screenshot or copy/paste your PowerShell session so we can help troubleshoot this issue?

**Comment by siddeshn** [comment]
![image](https://user-images.githubusercontent.com/37383104/105052011-49ba2780-5a67-11eb-8a3f-07f927a8ca0a.png)

**Comment by siddeshn** [comment]
![image](https://user-images.githubusercontent.com/37383104/105056561-41b0b680-5a6c-11eb-8f39-43586ab4ecca.png)

**Comment by genericdevname** [comment]
Can you run `install-module AzureAD`?

**Comment by siddeshn** [comment]
it's installed already
![image](https://user-images.githubusercontent.com/37383104/105059325-1085b580-5a6f-11eb-8335-6ec4b7193557.png)

**Comment by genericdevname** [comment]
What version is your AzureAD module?

**Comment by siddeshn** [comment]
Get-Module -Name AzureADPreview
![image](https://user-images.githubusercontent.com/37383104/105061786-cfdb6b80-5a71-11eb-9011-82e906b562b2.png)

**Comment by genericdevname** [comment]
Would recommend uninstalling AzureADPreview and installing the latest AzureAD module. Please let me know how it goes.

**Comment by siddeshn** [comment]
![image](https://user-images.githubusercontent.com/37383104/105062062-16c96100-5a72-11eb-8c93-31b974fc5db2.png)

**Comment by siddeshn** [comment]
Will do. Thanks
 
 
  On Tue, 19 Jan 2021 at 9:49 pm, genericdevname<notifications@github.com> wrote:   


Would recommend uninstalling AzureADPreview and installing the latest AzureAD module. Please let me know how it goes.

**Comment by siddeshn** [comment]
Yeah Now following issue
![image](https://user-images.githubusercontent.com/37383104/105622191-15e45680-5e07-11eb-97dd-140f29581cec.png)

**Comment by Zharick407** [comment]
For those others having this issue, you can run `Import-Module AzureADPreview` before running the Sparrow tool and it works as a workaround.

**Comment by genericdevname** [comment]
Only use PowerShell 5.1 and the AzureAD module (Not AzureADPreview).

**Comment by genericdevname** [comment]
Hello, we have not heard back from you regarding this issue. If no response is given within three days, I will go ahead and close out this issue.

**Comment by siddeshn** [comment]
Thanks. You can close. I worked it out on a diff machine

Sent from Yahoo Mail on Android 
 
  On Wed, 3 Feb 2021 at 9:34 pm, genericdevname<notifications@github.com> wrote:   


Hello, we have not heard back from you regarding this issue. If no response is given within three days, I will go ahead and close out this issue.
