### ISSUE TITLE
What exactly is the expected powershell output? 

### ISSUE THREAD

**Issue by scurityn00b** [cisagov/Sparrow#58]
Do you have an Office 365/Microsoft 365 E5/G5 license? Y/N: Y
Would you like to investigate a certain application? Y/N: N
Skipping AppID investigation

VERBOSE: Searching for 'Set domain authentication' and 'Set federation settings on domain' operations in the UAL.
VERBOSE: Searching for 'Update application' and 'Update application ? Certificates and secrets management' in the UAL.
VERBOSE: Searching for 'Update service principal' and 'Add service principal credentials' in the UAL.
VERBOSE: Searching for 'Add app role assignment to service principal', 'Add app role assignment grant to user', and 'Add app role assignment to group' in the UAL.
VERBOSE: Searching for 'Add OAuth2PermissionGrant' and 'Consent to application' in the UAL.
VERBOSE: Searching for 16457 in UserLoggedIn and UserLoginFailed operations in the UAL.
VERBOSE: Searching for PowerShell logins into mailboxes in the UAL.
VERBOSE: Searching for PowerShell logins using known PS application ids in the UAL.

Once I make the selections above, all I receive are details of my personal account using the headers detailed below:
Account              Environment TenantId                             TenantDomain         AccountType
-------              ----------- --------                             ------------         -----------

**Comment by tchamness** [comment]
Hello, 

I am running in to the same issue.

EDIT:
This was an issue with my local install of Office ProPlus. I ran an Office repair and the issue was resolved. Hope it works for everyone else.

**Comment by ttto65812** [comment]
We are having similar issues.  Can someone from CISA gives us an expected output?  What if nothing was found?  What should the results look like?

**Comment by BrendanChambersBourgeois** [comment]
It tells you what it is it currently doing, The script will create a folder where you ran it called ExportDir and will contain all the data it found. Its up to you to find out if these actions have be done by people in your company or if they are malicious.

**Comment by Zharick407** [comment]
> 
> 
> It tells you what it is it currently doing, The script will create a folder where you ran it called ExportDir and will contain all the data it found. Its up to you to find out if these actions have be done by people in your company or if they are malicious.

The script actually creates a folder in your Desktop, not in the folder you ran the script from.

**Comment by schupat** [comment]
> > It tells you what it is it currently doing, The script will create a folder where you ran it called ExportDir and will contain all the data it found. Its up to you to find out if these actions have be done by people in your company or if they are malicious.
> 
> The script actually creates a folder in your Desktop, not in the folder you ran the script from.

Oh man...this was really helpful. I was executing the script like a 3times and just no output. This should be added to the Readme.

**Comment by scurityn00b** [comment]
Roger that! I completely missed the folder creation but have found each of the directories and documents contained therein. Many thanks for that extra piece of information! It has proved to be invaluable in this procedure!

**Comment by genericdevname** [comment]
For how to interpret the results, the following alert will assist you: https://us-cert.cisa.gov/ncas/alerts/aa21-008a

The newly updated readme now states: `The tool then outputs the data into multiple CSV files that are located in the user's default home directory in a folder called 'ExportDir' (ie: Desktop/ExportDir).`
