### ISSUE TITLE
Report Entries should be de-dupped and sorted

### ISSUE THREAD

**Issue by chase-haitch-m** [cisagov/Sparrow#6]
# 🚀 Feature Proposal

I noticed that there were duplicate entries per Unified log event in SAMLToken_Operations_Export.csv. These entries should be de-duplicated and sorted with | Sort-Object -Unique . If other reports contain duplicate values, then they should similarly be sorted and de-duplicated.

## Motivation

It's overwhelming to look at a mess of data in rows of a .csv file. Let's try to make this as clean as possible.

**Comment by DeemOnSecurity** [comment]
We will be leaving it to the end user to manipulate the data as they see fit, as the objective of this project is to simply retrieve artifacts. If you wish to deduplicate the values, it is relatively simple to do in Excel. You can find the instructions [here](https://support.microsoft.com/en-us/office/find-and-remove-duplicates-00e35bea-b46a-4d5d-b28e-66a552dc138d)
