### ISSUE TITLE
Readme Update - Explicit Export Information

### ISSUE THREAD

**Issue by haydanbarry** [cisagov/Sparrow#60]
# 💡 Summary #

Modify the readme file to include detailed information on where the Export CSV file will be saved to.

## Motivation and context ##

The PS1 file does explain where the export is saved... however, it would be nice to spell out upfront where the export gets saved.
This would save a lot of time.

## Implementation notes ##

Modify this line in the readme
The tool then outputs the data into multiple CSV files in a default directory.

Updated
The tool outputs the data into multiple CSV files that are located in the user's default home directory in a folder called 'ExportDir' (ie: Desktop/ExportDir).

## Acceptance criteria ##

How do we know when this work is done?

- [ ] Criterion

**Comment by genericdevname** [comment]
Added the change to the readme.
