### ISSUE TITLE
"Choose Your Environment" comes up blank if AzureADPreview is installed instead of AzureAD module

### ISSUE THREAD

**Issue by Zharick407** [cisagov/Sparrow#61]
# 🐛 Summary #

What's wrong? The script fails to install AzureAD module naturally since the AzureADPreview contains the same cmdlets, then the script tries to import the AzureAD module and failts and has no logic to import AzureADPreview instead if present.

## To reproduce ##

1. Have AzureADPreview installed instead of AzureAD
1. Run the tool

## Expected behavior ##

Load the correct AzureADPreview module

**Comment by genericdevname** [comment]
Please use AzureAD instead.
