### ISSUE TITLE
Add docs on how to setup/retreive credentials

### ISSUE THREAD

**Issue by daixtrose** [cisagov/Sparrow#62]
# 💡 Summary #

Explain what to do when prompted for `InlineCredential`.

## Motivation and context ##

When running the script `Sparrow.ps1`in an online shell, the user gets prompted with the following output:

```powershell
...
cmdlet New-ExoPSSession at command pipeline position 1
Supply values for the following parameters:
(Type !? for Help.)
InlineCredential:
``` 

Why does this work belong in this project? I think that many should check their environment ASAP and might get stuck without that information.

This would be useful because most people are lost in the Azure admin center anyway and maybe have no clue how to continue with a script.

## Acceptance criteria ##

How do we know when this work is done?

- [ ] Docs contain additional steps to set up things in an Azure online shell environment

**Comment by genericdevname** [comment]
Hello, what do you mean by the Azure online shell environment?

This script was designed to be run from an analysis machine using PowerShell 5.1.

**Comment by genericdevname** [comment]
Hello, we have not heard back from you regarding this issue. If no response is given within three days, I will go ahead and close out this issue.
