### ISSUE TITLE
New-ExoPSSession : Access is denied

### ISSUE THREAD

**Issue by loteksys** [cisagov/Sparrow#63]
# 🐛 Summary #

What's wrong? Please be specific.
New-ExoPSSession : Connecting to remote server outlook.office365.com failed with the following error message : Access
is denied. For more information, see the about_Remote_Troubleshooting Help topic.

## To reproduce ##

1. Log into Office 365 in another window, make sure your password works.
1. Run script:
PS C:\Users\winny> Invoke-WebRequest 'https://github.com/cisagov/Sparrow/raw/develop/Sparrow.ps1' -OutFile 'Sparrow.ps1' -UseBasicParsing; .\Sparrow.ps1                                                                                        VERBOSE: Populating RepositorySourceLocation property for module ExchangeOnlineManagement.
...
Choose your Exchange Environment [O365Default]:

----------------------------------------------------------------------------
The module allows access to all existing remote PowerShell (V1) cmdlets in addition to the 9 new, faster, and more reliable cmdlets.

|--------------------------------------------------------------------------|
|    Old Cmdlets                    |    New/Reliable/Faster Cmdlets       |
|--------------------------------------------------------------------------|
|    Get-CASMailbox                 |    Get-EXOCASMailbox                 |
|    Get-Mailbox                    |    Get-EXOMailbox                    |
|    Get-MailboxFolderPermission    |    Get-EXOMailboxFolderPermission    |
|    Get-MailboxFolderStatistics    |    Get-EXOMailboxFolderStatistics    |
|    Get-MailboxPermission          |    Get-EXOMailboxPermission          |
|    Get-MailboxStatistics          |    Get-EXOMailboxStatistics          |
|    Get-MobileDeviceStatistics     |    Get-EXOMobileDeviceStatistics     |
|    Get-Recipient                  |    Get-EXORecipient                  |
|    Get-RecipientPermission        |    Get-EXORecipientPermission        |
|--------------------------------------------------------------------------|

To get additional information, run: Get-Help Connect-ExchangeOnline or check https://aka.ms/exops-docs

Send your product improvement suggestions and feedback to exocmdletpreview@service.microsoft.com. For issues related to the module, contact Microsoft support. Don't use the feedback alias for problems or support issues.
----------------------------------------------------------------------------

New-ExoPSSession : Connecting to remote server outlook.office365.com failed with the following error message : Access
is denied. For more information, see the about_Remote_Troubleshooting Help topic.
At C:\Program Files\WindowsPowerShell\Modules\ExchangeOnlineManagement\2.0.3\ExchangeOnlineManagement.psm1:426 char:30
+ ... PSSession = New-ExoPSSession -ExchangeEnvironmentName $ExchangeEnviro ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [New-ExoPSSession], PSRemotingTransportException
    + FullyQualifiedErrorId : System.Management.Automation.Remoting.PSRemotingDataStructureException,Microsoft.Exchang
   e.Management.ExoPowershellSnapin.NewExoPSSession

PS C:\Users\winny>

## Expected behavior ##

1 - return code success

Add any screenshots of the problem here.
![image](https://user-images.githubusercontent.com/30931008/107268825-53073600-6a0e-11eb-85db-cacb234a675b.png)

**Comment by genericdevname** [comment]
Hello, it looks like you might have a permissions issue with your environment. Please ensure the account you are using to run Sparrow has the following permissions as detailed by the readme:


```
    Azure Active Directory:
        Security Reader
    Security and Compliance Center:
        Compliance Administrator
    Exchange Online Admin Center: Utilize a custom group for these specific permissions:
        Mail Recipients
        Security Group Creation and Membership
        User options
        View-Only Audit log
        View-Only Configuration
        View-Only Recipients

```

If you already have these permissions, I would also recommend to check if the account has permissions to run PowerShell in the Exchange Online environment: https://docs.microsoft.com/en-us/powershell/exchange/disable-access-to-exchange-online-powershell?view=exchange-ps

**Comment by genericdevname** [comment]
Are you still experiencing this issue?

**Comment by genericdevname** [comment]
Hello, we have not heard back from you regarding this issue. If no response is given within three days, I will go ahead and close out this issue.
