### ISSUE TITLE
AppId's in PSLogin_Operations_Export query not in results

### ISSUE THREAD

**Issue by Dingersville** [cisagov/Sparrow#64]
# 🐛 Summary #

We have the E3 license for M365.

We’re looking at the output of the Sparrow tool reports. In PSLogin_Operations_Export.csv, we should be seeing the results of the three queries:

-FreeText "a0c73c16-a7e3-4564-9a95-2bdf47383716"
-FreeText "1b730954-1685-4b74-9bfd-dac224a7b894"
-FreeText "WinRM"

So in the single csv that all of those are put into, we see some rows containing the string WinRM. There are a lot of other rows that don’t have any of those three FreeText strings. If a row in the output does not contain WinRM, shouldn’t it contain one of the first two strings? None of them do.

Thanks for your assistance.

## To reproduce ##

We ran the Sparrow tool unmodified

## Expected behavior ##

In the PSLogin_Operations_Export, any rows that don't have the string WinRM should have one of the other two AppID strings that make up the PSLogin_Operations_Export, but those AppIDs (for Exchange Online PowerShell and PowerShell) are nowhere in the output.

## Any helpful log output or screenshots ##

Paste the results here:

```console

```

Add any screenshots of the problem here.

**Comment by genericdevname** [comment]
Hello, I added some logic to eliminate CSVs that have no data and add some logging with regards to the PowerShell pull.

If you want, you can re-run Sparrow to see if the verbose logging added helps answer your question.

**Comment by Dingersville** [comment]
Thanks. I'll have a colleague run the new build. I want to make sure it's clear that in PSLogin_Operations_Export, we have many rows which obviously do contain data (otherwise they wouldn't be rows at all), but none of the three FreeText strings. I'm not referring to blank rows or anything blank.

**Comment by genericdevname** [comment]
I added a new ApplicationId column to assist you with looking at the CSV output. I merged the pull request that fixes this issue. Please re-run Sparrow to see if this addition helps answer your question.

**Comment by genericdevname** [comment]
Hello, we have not heard back from you regarding this issue. If no response is given within three days, I will go ahead and close out this issue.

**Comment by Dingersville** [comment]
We have run the new reports and indeed there is a column for Application ID. A bit strange no one noticed that.

Thanks for fixing!
