### ISSUE TITLE
Issue while running sparrow.ps1

### ISSUE THREAD

**Issue by Vinod-o365** [cisagov/Sparrow#68]
Hi Team,
We are getting warning : Result set may have been truncated; narrow start/end date

**Comment by genericdevname** [comment]
Hello,

The warning message is alerting you that there were 5000 entries returned, which is the maximum amount of results that Search-UnifiedAuditLog will return.

If you modify the following code (lines 7 and 9), you will be able to return results that are more narrow. If you wanted to attempt to capture all the results, you will have to run the script multiple times with different date ranges:
```
    [Parameter()]
    [datetime] $StartDate = [DateTime]::UtcNow.AddDays(-364),
    [Parameter()]
    [datetime] $EndDate = [DateTime]::UtcNow,
```
