### ISSUE TITLE
Error output from PS1 execution

### ISSUE THREAD

**Issue by cdev45** [cisagov/Sparrow#7]
Hi,

We are attempting to run 'C:\temp\Sparrow.ps1', however we continue to receive the following error:

![image](https://user-images.githubusercontent.com/28009948/103155053-29e65b00-476a-11eb-9ea7-ad89f8c7d0c3.png)

**Comment by volleronline** [comment]
I get this same series of errors in PowerShell 5.1
My full version: 5.1.19041.610

**Comment by overflowingInt** [comment]
Have you tried https://raw.githubusercontent.com/cisagov/Sparrow/develop/Sparrow.ps1 ? It looks like you have the HTML file from the page instead of the raw ps1

**Comment by cdev45** [comment]
> Have you tried https://raw.githubusercontent.com/cisagov/Sparrow/develop/Sparrow.ps1 ? It looks like you have the HTML file from the page instead of the raw ps1

Thanks @overflowingInt. That was the problem! I've never experienced that issue, but grateful it was a simple fix. Thanks.
