### ISSUE TITLE
Run via Taskmanager 

### ISSUE THREAD

**Issue by srfn8kd** [cisagov/Sparrow#70]
Would it be possible to provide succinct instructions/capability within the script so that it functions independently of any user having to manually click on the script to run it?  Since this data is being imported into Splunk, it'd be far better if the data could be retrieved and sent to Splunk via scheduled tasks.  We already do this with other data exports from o365 to Splunk, works great, I just need the ability to use stored credentials instead of having to manually enter credentials 3x every time we want to run the script and there is something about PS v2 that differs from PS v1 so that the method we use with PS v1 scripts won't work with this one.

Thanks in advance for your consideration.

**Comment by PwshPally** [comment]
@srfn8kd are you able to put your store credentials into a PowerShell Credential object which could be passed to this?
