### ISSUE TITLE
How to Upload Dashboard

### ISSUE THREAD

**Issue by HMackNoHVAC** [cisagov/Sparrow#76]
# 🐛 Summary #

What's wrong? Please be specific.

I am having a hard time understanding how to create/download the dashboard. I ran the sparrow script and have the csv logs but now I do not know what to do with the aviary xml script. 

Also, once I ran the sparrow script and when it was retrieving the data, I received this error message.

"WARNING: There were errors during the search process which might affect the validity of the data."

Do I need a splunk account to create the dashboard? Please assist. Thanks!

## To reproduce ##

1. Do this
1. Then this

## Expected behavior ##

What did you expect to happen that didn't?

## Any helpful log output or screenshots ##

Paste the results here:

```console

```

Add any screenshots of the problem here.

**Comment by genericdevname** [comment]
Hi,

The aviary xml script is for the Splunk dashboard and you will need Splunk in order to use it.

Thank you.

**Comment by HMackNoHVAC** [comment]
Where can I download splunk?

**Comment by SergGu** [comment]
https://www.splunk.com/en_en/goto/Download_4_2
