### ISSUE TITLE
How do I ingest the csv files into the dashboard?

### ISSUE THREAD

**Issue by HMackNoHVAC** [cisagov/Sparrow#77]
# 🐛 Summary #

What's wrong? Please be specific.

I am having a hard time ingesting the csv files from the PowerShell script to the aviary dashboard

![image](https://user-images.githubusercontent.com/87460161/126566806-31d1a06c-c269-4a99-9da7-c235bb343104.png)

Circled are the directions but as you can see I am getting error messages on the data output on the dashboard.

Please help when you can. Thank you.

## To reproduce ##

1. Do this
1. Then this

## Expected behavior ##

What did you expect to happen that didn't?

## Any helpful log output or screenshots ##

Paste the results here:

```console

```

Add any screenshots of the problem here.

**Comment by SergGu** [comment]
This "dashbord" requires Splunk software installed and full functional. Downloading and installing Splunk (free) is a good start.
https://www.splunk.com/en_en/goto/Download_4_2

**Comment by neestermans** [comment]
You forgot to select a data ingest point. Upload your CSV files http://127.0.0.1:8000/en-US/manager/search/adddata here and then create a new index. Once all data is uploaded, you can then read the report.
